apiVersion: v1
kind: ConfigMap
metadata:
  name: car-repair-shop-config
  namespace: car-repair-shop
  labels:
    app.kubernetes.io/part-of: fiap-tech-challenge
data:
  PORT: "3000"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  OTEL_SERVICE_NAME: "car-repair-shop-api"
  ADMIN_EMAIL: "admin@master.com"
  CORS_ORIGIN: ""
