sonar.projectKey=fiap-tech-challenge
sonar.projectName=Car Repair Shop API
sonar.sources=src
sonar.tests=tests
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**,node_modules/**,coverage/**
sonar.coverage.exclusions=src/main.ts,src/app.ts,src/frameworks/http/swagger/**,src/frameworks/database/connection.ts,src/frameworks/database/seed.ts,src/frameworks/database/models/**
